-- Allo Psycho V5.1 — accès Premium minimal, sans données psychologiques
create table if not exists public.premium_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  trial_started_at timestamptz not null default now(),
  premium_until timestamptz,
  source text not null default 'trial' check (source in ('trial','code','manual')),
  updated_at timestamptz not null default now()
);

create table if not exists public.premium_codes (
  id bigint generated by default as identity primary key,
  code_hash text not null unique,
  duration_days integer not null default 31 check (duration_days between 1 and 3660),
  expires_at timestamptz,
  redeemed_by uuid references auth.users(id) on delete set null,
  redeemed_at timestamptz,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.premium_entitlements enable row level security;
alter table public.premium_codes enable row level security;
revoke all on public.premium_entitlements from anon, authenticated;
revoke all on public.premium_codes from anon, authenticated;
-- Ces tables sont accessibles uniquement via la fonction premium-access (service role).
